[package]
edition = "2021"
name = "htlnm"
version = "0.1.0"

[dependencies]
anyhow = "1.0.81"
chrono = {version = "0.4.35", features = ["serde", "clock"]}
clap = {version = "4.4.18", features = ["derive", "string"]}
dirs = "5.0.1"
handlebars = "5.1.0"
reqwest = {version = "0.11.23", features = ["json", "blocking"]}
rfc822-like = "0.2.1"
rfc822_sanitizer = "0.3.6"
rpassword = "7.3.1"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"
